#!/usr/bin/env python3
"""Slice W: apply the canonicalization merge proposal generated by
analyze_entity_canonicalization.py. Performs:
  1. pg_dump snapshot (mandatory per v2 plan §0 pre-migration gate).
  2. Per merge group, redirect chunk_entities + thought_entities edges to the
     canonical entity (idempotent: ON CONFLICT keeps the higher weight).
  3. Delete the alias entity rows.
  4. Recompute entities.mentions_count from the union of post-merge edges.
  5. Verify gate: distinct entity reduction >= 3%.

Usage:
  python3 apply_entity_canonicalization.py --proposal /tmp/entity_merge_proposal.json
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import time
from pathlib import Path

import psycopg


def load_env(path: Path) -> dict[str, str]:
    env: dict[str, str] = {}
    if not path.exists():
        return env
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        env[k] = v.strip().strip('"')
    return env


def connect(env):
    return psycopg.connect(
        host=env.get("DB_HOST", "127.0.0.1"),
        port=int(env.get("DB_PORT", "5432")),
        user=env["DB_USER"],
        password=env["DB_PASSWORD"],
        dbname=env["DB_NAME"],
    )


def pg_dump(env, label: str) -> Path:
    backup_dir = Path(os.path.expanduser("~/.openbrain-backups"))
    backup_dir.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    dump_path = backup_dir / f"pre-{label}-{ts}.dump"
    cmd = [
        "pg_dump",
        "-Fc",
        "-h",
        env.get("DB_HOST", "127.0.0.1"),
        "-p",
        env.get("DB_PORT", "5432"),
        "-U",
        env["DB_USER"],
        env["DB_NAME"],
        "-f",
        str(dump_path),
    ]
    subprocess.run(cmd, check=True, env={**os.environ, "PGPASSWORD": env["DB_PASSWORD"]})
    size = dump_path.stat().st_size
    if size < 1_000_000:
        raise RuntimeError(f"pg_dump too small ({size} bytes)")
    subprocess.run(["pg_restore", "--list", str(dump_path)], check=True, stdout=subprocess.DEVNULL)
    print(f"[apply] backup OK: {dump_path} ({size:,} bytes)")
    return dump_path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--proposal", default="/tmp/entity_merge_proposal.json")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    proposal = json.loads(Path(args.proposal).read_text())
    merges = proposal["merges"]
    summary = proposal["summary"]
    print(f"[apply] loaded proposal: {len(merges)} groups, expected reduction {summary['pct_reduction_if_applied']}%")

    env = load_env(Path(os.path.expanduser("~/workspace/openbrain/.env")))

    if not args.dry_run:
        pg_dump(env, "slice-w-entity-canonicalization")

    conn = connect(env)
    conn.autocommit = False
    cur = conn.cursor()

    cur.execute("SELECT count(*) FROM entities")
    pre_entities = cur.fetchone()[0]
    cur.execute("SELECT count(*) FROM chunk_entities")
    pre_chunk_links = cur.fetchone()[0]
    cur.execute("SELECT count(*) FROM thought_entities")
    pre_thought_links = cur.fetchone()[0]
    print(f"[apply] pre: entities={pre_entities} chunk_links={pre_chunk_links} thought_links={pre_thought_links}")

    if args.dry_run:
        print("[apply] dry-run only, no DB changes")
        return 0

    redirected_chunk_links = 0
    redirected_thought_links = 0
    deleted_alias_entities = 0

    try:
        for i, group in enumerate(merges, 1):
            canonical_id = group["canonical_id"]
            alias_ids = [a["id"] for a in group["aliases"]]
            if not alias_ids:
                continue

            # Redirect chunk_entities: insert (chunk_id, canonical_id) for every
            # (chunk_id, alias_id), keep the higher weight on conflict, then
            # the alias rows will be removed by cascade when we delete the
            # alias entity. We perform the SELECT explicitly so we can count.
            cur.execute(
                """
                WITH alias_links AS (
                    SELECT DISTINCT chunk_id FROM chunk_entities WHERE entity_id = ANY(%s)
                )
                INSERT INTO chunk_entities (chunk_id, entity_id, weight)
                SELECT chunk_id, %s, 1.0 FROM alias_links
                ON CONFLICT (chunk_id, entity_id) DO NOTHING
                """,
                [alias_ids, canonical_id],
            )
            redirected_chunk_links += cur.rowcount or 0

            cur.execute(
                """
                WITH alias_links AS (
                    SELECT DISTINCT thought_id FROM thought_entities WHERE entity_id = ANY(%s)
                )
                INSERT INTO thought_entities (thought_id, entity_id, relationship, weight)
                SELECT thought_id, %s, 'mentions', 1.0 FROM alias_links
                ON CONFLICT (thought_id, entity_id) DO NOTHING
                """,
                [alias_ids, canonical_id],
            )
            redirected_thought_links += cur.rowcount or 0

            cur.execute("DELETE FROM entities WHERE id = ANY(%s)", [alias_ids])
            deleted_alias_entities += cur.rowcount or 0

            if i % 100 == 0:
                print(f"[apply] processed {i}/{len(merges)} groups")

        # Recompute mentions_count = union of distinct chunk + thought edges
        # (DELETE cascade removed alias edges; canonical now holds the union).
        print("[apply] recomputing entities.mentions_count from edge unions")
        cur.execute(
            """
            UPDATE entities e
               SET mentions_count = COALESCE(c.cnt, 0) + COALESCE(t.cnt, 0)
              FROM (SELECT entity_id, count(*) AS cnt FROM chunk_entities GROUP BY entity_id) c
              FULL JOIN (SELECT entity_id, count(*) AS cnt FROM thought_entities GROUP BY entity_id) t
                ON c.entity_id = t.entity_id
             WHERE e.id = COALESCE(c.entity_id, t.entity_id)
            """,
        )
        # Zero out entities with no remaining edges
        cur.execute(
            """
            UPDATE entities
               SET mentions_count = 0
             WHERE id NOT IN (SELECT entity_id FROM chunk_entities UNION SELECT entity_id FROM thought_entities)
            """,
        )

        conn.commit()
        print(f"[apply] committed: redirected_chunk_links={redirected_chunk_links} redirected_thought_links={redirected_thought_links} deleted_alias_entities={deleted_alias_entities}")
    except Exception:
        conn.rollback()
        raise

    cur.execute("SELECT count(*) FROM entities")
    post_entities = cur.fetchone()[0]
    cur.execute("SELECT count(*) FROM chunk_entities")
    post_chunk_links = cur.fetchone()[0]
    cur.execute("SELECT count(*) FROM thought_entities")
    post_thought_links = cur.fetchone()[0]

    reduction = pre_entities - post_entities
    pct = 100 * reduction / pre_entities if pre_entities else 0
    gate_pass = pct >= 3.0
    print(f"[apply] post: entities={post_entities} chunk_links={post_chunk_links} thought_links={post_thought_links}")
    print(f"[apply] reduction: {reduction} entities ({pct:.2f}%) — gate {'PASS' if gate_pass else 'FAIL'} (target >=3%)")

    return 0 if gate_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
